import io
from datetime import date

import pandas as pd
from fpdf import FPDF

from src.ui import strip_status_emoji


class _PO(FPDF):
    def __init__(self, po_number, today, lead_time, service_level, store_filter):
        super().__init__()
        self.po_number = po_number
        self.today = today
        self.lead_time = lead_time
        self.service_level = service_level
        self.store_filter = store_filter

    def header(self):
        self.set_fill_color(30, 58, 95)          # #1E3A5F
        self.rect(0, 0, 210, 28, "F")
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 7)
        self.cell(100, 8, "PURCHASE ORDER", ln=0)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(180, 200, 220)
        self.set_xy(10, 17)
        self.cell(100, 5, "ForecastIQ - Supply Chain Intelligence")

        # Right-side meta
        self.set_font("Helvetica", "", 8)
        self.set_text_color(255, 255, 255)
        meta = [
            ("PO Number:", self.po_number),
            ("Date:", self.today),
            ("Lead time:", f"{self.lead_time} days"),
            ("Service level:", f"{int(self.service_level * 100)}%"),
            ("Store:", self.store_filter),
        ]
        y = 4
        for label, value in meta:
            self.set_xy(130, y)
            self.set_font("Helvetica", "B", 7)
            self.set_text_color(160, 190, 220)
            self.cell(30, 4, label, ln=0)
            self.set_font("Helvetica", "", 7)
            self.set_text_color(255, 255, 255)
            self.cell(40, 4, value, ln=0)
            y += 4.5

        self.ln(5)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 163, 184)
        self.cell(0, 5,
                  f"Generated by ForecastIQ on {self.today} | "
                  "Quantities based on ensemble ML forecast + EOQ safety stock",
                  align="C")


_ABC_COLORS = {
    "A": (254, 226, 226),   # light red
    "B": (254, 249, 195),   # light yellow
    "C": (239, 246, 255),   # light blue
}

_COLS = [
    ("Product",        52, "L"),
    ("Store",          18, "C"),
    ("ABC",             9, "C"),
    ("Order Qty",      20, "R"),
    ("Unit Price ($)", 24, "R"),
    ("Total ($)",      24, "R"),
    ("Status",         28, "C"),
]


def generate_po_pdf(
    df: pd.DataFrame,
    lead_time: int,
    service_level: float,
    store_filter: str,
) -> bytes:
    today = date.today().strftime("%B %d, %Y")
    po_number = f"PO-{date.today().strftime('%Y%m%d')}-{abs(hash(store_filter)) % 1000:03d}"
    total_value = df["Total ($)"].sum()

    pdf = _PO(po_number, today, lead_time, service_level, store_filter)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(10, 32, 10)

    # ── Column headers ────────────────────────────────────────────────────────
    pdf.set_y(32)
    pdf.set_fill_color(30, 58, 95)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    for col, width, align in _COLS:
        pdf.cell(width, 7, col, border=0, align=align, fill=True)
    pdf.ln()

    # ── Data rows ─────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 8)
    for i, row in df.iterrows():
        abc = str(row.get("ABC", ""))
        r, g, b = _ABC_COLORS.get(abc, (255, 255, 255))
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(30, 41, 59)

        values = [
            str(row["Product"]),
            str(row["Store"]),
            abc,
            str(int(row["Order Qty"])),
            f"${row['Unit Price ($)']:.2f}",
            f"${row['Total ($)']:.2f}",
            strip_status_emoji(str(row["Status"])),
        ]
        for (_, width, align), val in zip(_COLS, values):
            pdf.cell(width, 6, val, border="B", align=align, fill=True)
        pdf.ln()

    # ── Summary ───────────────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 58, 95)
    pdf.set_x(10)
    pdf.cell(143, 7, "ORDER TOTAL", align="R")
    pdf.cell(24, 7, f"${total_value:,.2f}", align="R")
    pdf.ln(10)

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.getvalue()
